<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldFocusReasearchSeeder extends Seeder
{
    /*
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemanfaatan teknik radiasi untuk pencarian galur mutan unggul","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan tanaman dengan teknologi berbasis bioteknologi","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan tanaman teknik konvensional","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan tanaman","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan ternak dengan teknologi berbasis bioteknologi","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan ternak teknik konvensional","category_research_id"=>"1"],
["research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan ternak","category_research_id"=>"1"],
["research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Modernisasi sistem pertanian dan pemanfaatan lahan","category_research_id"=>"1"],
["research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Pertanian lahan sub-optimal basah","category_research_id"=>"1"],
["research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Optimasi sistem pertanian tropis","category_research_id"=>"1"],
["research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Optimasi sistem pertanian tropis pada komunitas perempuan untuk ketahanan pangan keluarga berbasis pengetahuan lokal","category_research_id"=>"1"],
["research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Penggunaan kearifan lokal dalam memanfaatkan dan melestarikan lahan dalam rangka keberlanjutan","category_research_id"=>"1"],
["research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pengembangan identitas fungsional pertanian","category_research_id"=>"1"],
["research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Transformasi antar generasi pekerja pertanian","category_research_id"=>"1"],
["research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pergeseran pekerjaan pertanian pada perempuan petani","category_research_id"=>"1"],
["research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Keanekaragaman pangan berbasis sumber daya tanaman lokal melalui peran komunitas, perempuan, dan keluarga","category_research_id"=>"1"],
["research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pola pengembangan SDM Pertanian pada masyarakat tradisional/lokal","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Penguatan agroindustri berbahan baku sumber daya lokal","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Pengelolaan dan konservasi sumber daya lahan, air, dan hayati","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Precision agriculture","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Rekayasa mesin-mesin pertanian dan pengolahan","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Teknologi iradiasi pengawetan hasil pertanian","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Diversifikasi dan hilirisasi produk pertanian, perkebunan, peternakan, dan perikanan","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Revitalisasi dan penguatan pengetahuan lokal perempuan petani","category_research_id"=>"1"],
["research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Pengelolaan, konservasi sumber daya, dan hilirisasi produk berbasis kearifan lokal","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pendukung kemandirian pangan (padi, jagung, dan kedelai) dan tanaman perkebunan","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Kemandirian pangan komoditas ruminansia","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Kemandirian pangan komoditas perairan","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Efisiensi rantai nilai hasil pertanian, perkebunan, peternakan","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan produk pangan berbasis sumber daya tropis","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan produk pangan fungsional","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan teknologi untuk deteksi pemalsuan produk pertanian, peternakan, dan perikanan","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan teknologi untuk pengujian produk halal","category_research_id"=>"1"],
["research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Strategi ketahanan dan kemandirian pangan pada masyarakat tradisional","category_research_id"=>"1"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Teknologi pendukung konversi ke bahan bakar gas (BBG)","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Dimethyl ether untuk energi rumah tangga dan transportasi","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan komponen converter kit","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi dan produk biogasoline","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan dan pemanfaatan bioenergi untuk transportasi, listrik dan industri","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi dan pemanfaatan fuel cell","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi pembuatan bio-crude oil","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi pembuatan bioetanol generasi","category_research_id"=>"2"],
["research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan bahan bakar lokal sebagai substituent bahan bakar fosil","category_research_id"=>"2"],
["research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLT panas bumi","category_research_id"=>"2"],
["research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLT mikro hidro darat dan marine","category_research_id"=>"2"],
["research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"PLT bioenergi (biomass, biogas, biofuel) masif","category_research_id"=>"2"],
["research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLTB (Bayu)","category_research_id"=>"2"],
["research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Restorasi lahan dan inisiasi pengembangan energi listrik berbasis sumber daya lokal","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Bangunan hemat dan mandiri energi","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Sistem smart grid dan manajemen konservasi energi","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Teknologi komponen listrik hemat energi","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Pengembangan sistem microgrid dalam manajemen energi terbarukan","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Teknologi hybrid dalam pemanfaatan sumber energi terbarukan","category_research_id"=>"2"],
["research_theme"=>"Teknologi konservasi energi","research_topic"=>"Kearifan lokal dalam arsitektur untuk pengembangan bangunan hemat energi","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pendukung EOR","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Penyiapan infrastruktur PLTN","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pendukung clean coal","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Transfer dan adopsi inovasi diversifikasi energi berbasis komunitas berwawasan gender dan berkelanjutan","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Model transformasi komunitas mandiri energi terbarukan berbasis pengetahuan lokal, komunitas dan masyarakat lokal","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pengembangan elektrifikasi pedesaan","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi tepat guna dalam pemanfaatan energi baru dan terbarukan","category_research_id"=>"2"],
["research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Pengelolaan energi terbarukan berbasis kearifan lokal masyarakat","category_research_id"=>"2"],
["research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan produksi vaksin utama (hepatitis, dengue)","category_research_id"=>"3"],
["research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan sel punca (stem cell)","category_research_id"=>"3"],
["research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan produk biosimilar dan produk darah","category_research_id"=>"3"],
["research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit infeksi","category_research_id"=>"3"],
["research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit degeneratif","category_research_id"=>"3"],
["research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan alat elektromedik","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan fitofarmaka berbasis sumber daya lokal","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Bahan baku obat kimia","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Saintifikasi jamu dan herbal, teknologi produksi pigmen alami","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan obat tradisional berbasis IPTEKS untuk penyakit-penyakit tropis (neglected diseases)","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan teknologi biosimilar, biosintesis, dan biorefinery untuk produksi bahan obat","category_research_id"=>"3"],
["research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Etnomedisin (daun, akar, umbi, batang, buah)","category_research_id"=>"3"],
["research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Penguatan pengetahuan perempuan dalam pengembangan fitofarmaka berbasis pengetahuan lokal","category_research_id"=>"3"],
["research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Pengetahuan lokal untuk penggunaan jamu dan herbal dalam kesehatan masyarakat, yang sensitif gender dan inklusif sosial","category_research_id"=>"3"],
["research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Penguatan pengetahuan dan pengembangan kebiasaan masyarakat dalam berperilaku sehat","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mendukung pola hidup bersih dan sehat","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mengatasi wabah penyakit","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mengatasi stunting dan pola asuh anak dalam keluarga.","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal kaitannya dengan pengolahan makanan sehat dan bergizi","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Identifikasi hambatan budaya dalam tumbuh kembang dan pola asuh anak","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan reproduksi perempuan","category_research_id"=>"3"],
["research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Pengetahuan perempuan tentang kesehatan reproduksi berbasis kearifan lokal","category_research_id"=>"3"],
["research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Manajemen keselamatan","category_research_id"=>"4"],
["research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Sarana prasarana pendukung keselamatan","category_research_id"=>"4"],
["research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Manajemen transportasi ramah gender, anak, dan kelompok berkebutuhan khusus","category_research_id"=>"4"],
["research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Kearifan lokal dalam mobilitas masyarakat tradisional","category_research_id"=>"4"],
["research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Adopsi nilai dan norma masyarakat lokal dalam mengembangkan manajemen keselamatan transportasi","category_research_id"=>"4"],
["research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda jalan dan rel","category_research_id"=>"4"],
["research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda air","category_research_id"=>"4"],
["research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda udara","category_research_id"=>"4"],
["research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Penguatan industri transportasi yang ramah lingkungan sosial dan budaya","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Sistem cerdas manajemen transportasi","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Teknologi prasarana transportasi","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Sistem konstruksi prasarana transportasi","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Manajemen keselamatan kerja pelaksanaan konstruksi infrastruktur","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Manajemen sistem pengendalian dan penjaminan mutu pelaksanaan konstruksi infrastruktur transportasi","category_research_id"=>"4"],
["research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Pelibatan tokoh-tokoh lokal dalam perencanaan pengembangan teknologi infrastruktur sistem transportasi","category_research_id"=>"4"],
["research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Riset dasar pendukung teknologi dan sistem transportasi","category_research_id"=>"4"],
["research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Sistem sosial yang mendukung partisipasi perempuan, anak, dan inklusi sosial serta dalam penggunaan sarana dan prasarana transportasi","category_research_id"=>"4"],
["research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Pengetahuan lokal untuk pengembangan kebijakan transportasi","category_research_id"=>"4"],
["research_theme"=>"Intelligent transportation system","research_topic"=>"Manajemen transportasi perkotaan/urban","category_research_id"=>"4"],
["research_theme"=>"Intelligent transportation system","research_topic"=>"Manajemen transportasi logistik","category_research_id"=>"4"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Teknologi 5G (broadband)","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Telekomunikasi berbasis Internet Protocol (IP) dan Internet of Things (IoT)","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Network, data and information security","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Penyiaran multimedia berbasis digital","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"IT security","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Pengembangan jaringan sensor","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Teknologi antena dan propagasi gelombang radio","category_research_id"=>"5"],
["research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Pengembangan sistem radio kognitif","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem TIK e-Government","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem TIK e-Business","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Framework/platform penunjang industri kreatif dan kontrol","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem informasi berbasis teknologi pendukung industri mikro berwawasan gender dan berkelanjutan","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem informasi berbasis kearifan lokal","category_research_id"=>"5"],
["research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Teknologi dan konten untuk data informasi geospasial dan inderaja","category_research_id"=>"5"],
["research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Pengembangan teknologi big data","category_research_id"=>"5"],
["research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Teknologi untuk data informasi berbagai bentuk kearifan lokal di Indonesia","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk sistem jaringan","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk smart city","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk customer premises equipment (CPE)","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Kebijakan dan sosial humaniora pendukung TIK","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Teknologi piranti pendukung partisipasi perempuan, anak, kelompok berkebutuhan khusus, serta keamanan penggunaan informasi berbasis TIK","category_research_id"=>"5"],
["research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk pelestarian kearifan lokal","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem berbasis kecerdasan buatan","research_topic"=>"Pengembangan aplikasi sistem cerdas","category_research_id"=>"5"],
["research_theme"=>"Pengembangan sistem berbasis kecerdasan buatan","research_topic"=>"Teknologi robot vision","category_research_id"=>"5"],
["research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra darat","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra laut","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra udara","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Adopsi sistem pengetahuan dan teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Sistem teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara yang ramah perempuan, anak, dan kelompok rentan","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk roket","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk handak","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk sistem persenjataan","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan produk Komando, Kendali, Komunikasi, Komputasi, Integrasi, Pengamatan, dan Pengintaian (K4IPP), terutama radar, alat komunikasi dan satelit","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan produk material","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan sumber daya pertahanan","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan sistem sosial pendukung pertahanan dan keamanan berbasis budaya lokal yang berwawasan gender dan inklusi sosial","category_research_id"=>"6"],
["research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Sistem hankam berbasis sistem pengetahuan dan teknologi lokal","category_research_id"=>"6"],
["research_theme"=>"Penanganan konflik melalui pendekatan sosial budaya","research_topic"=>"Identifikasi nilai-nilai kearifan lokal dalam penanganan konflik","category_research_id"=>"6"],
["research_theme"=>"Penanganan konflik melalui pendekatan sosial budaya","research_topic"=>"Adopsi nilai-nilai kearifan lokal untuk menangani konflik","category_research_id"=>"6"],
["research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Ekstraksi dan rancang bangun pabrik logam tanah jarang.","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Pengembangan sel surya berbasis non silicon","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Pengolahan bijih mineral strategis lokal","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Produksi polimer untuk aplikasi separasi di industri","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Material pendukung biosensor dan kemosensor","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan membran","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan katalisator dan biokatalisator (enzim) untuk aplikasi di industri","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Inovasi teknologi material bahan bangunan lokal","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Teknologi ekstraksi aspal dari batuan alami (aspal batu buton).","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan material geopolimer","category_research_id"=>"7"],
["research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Inovasi teknologi material bahan bangunan lokal.","category_research_id"=>"7"],
["research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Desain dan eksplorasi material pigmen absorber","category_research_id"=>"7"],
["research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Pendukung transformasi material sampah dan pengolahan limbah","category_research_id"=>"7"],
["research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Pendukung material struktur","category_research_id"=>"7"],
["research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Karakterisasi material berbasis laser dan optik.","category_research_id"=>"7"],
["research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Karakterisasi material biokompatibel","category_research_id"=>"7"],
["research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Kemandirian bahan baku magnet kuat.","category_research_id"=>"7"],
["research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Pengembangan material paduan","category_research_id"=>"7"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Ketahanan sosial dan penguatan ekonomi pesisir","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Kedaulatan pangan masyarakat pesisir dan pulau terpencil","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengelolaan pesisir perbatasan dari aspek social security dan prosperity","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Diversifikasi, dan pelestarian sumber daya kelautan","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Eksplorasi dan pemanfaatan sumber daya pesisir dan laut","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan teknologi dan manajemen pulaupulau kecil dan pesisir.","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan industri pariwisata bahari","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan industri pariwisata bahari di daerah 3T berbasis kearifan lokal","category_research_id"=>"8"],
["research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Sistem pengetahuan dan teknologi lokal dalam pelestarian sumber daya laut dan pesisir","category_research_id"=>"8"],
["research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Konservasi dan rehabilitasi ekosistem pesisir dan laut.","category_research_id"=>"8"],
["research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Zonasi ekosistem dan pendukung kawasan konservasi laut.","category_research_id"=>"8"],
["research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Teknologi konservasi dan rehabilitasi ekosistem pesisir dan laut berbasis kearifan lokal","category_research_id"=>"8"],
["research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Eksplorasi nilai-nilai kearifan lokal dalam pengelolaan dan pemanfaatan sumber daya laut dan pesisir.","category_research_id"=>"8"],
["research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Kesehatan dan jasa ekosistem pesisir dan laut","category_research_id"=>"8"],
["research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Penguasaan teknologi survei SDE/SDA laut dalam.","category_research_id"=>"8"],
["research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Pengembangan teknologi wahana pesisir, lepas pantai, dan laut dalam.","category_research_id"=>"8"],
["research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Penguasaan teknologi komunikasi, navigasi, security, dan supervise","category_research_id"=>"8"],
["research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Pengembangan teknologi infrastruktur pantai dan lepas pantai","category_research_id"=>"8"],
["research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Integrasi kearifan lokal dalam pengembangan teknologi infrastruktur, komunikasi, dan wahana maritim","category_research_id"=>"8"],
["research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Revitalisasi kearifan lokal untuk ketahanan, keluarga dan pelestarian sumber daya kelautan","category_research_id"=>"8"],
["research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan, kelompok minoritas, dan keluarga untuk ketahanan, dan diversifikasi produk pengolahan sumber daya kelautan","category_research_id"=>"8"],
["research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan, dan inklusi sosial dalam penerimaan dan pemanfaatan pariwisata bahari","category_research_id"=>"8"],
["research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Integrasi konservasi lingkungan maritim dalam kurikulum pendidikan yang berwawasan gender dan inklusi sosial.","category_research_id"=>"8"],
["research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan dalam pengembangan, pemeliharaan, dan penguatan infrastruktur pantai dan lepas pantai","category_research_id"=>"8"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Mitigasi pengurangan risiko bencana geologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Pencegahan dan kesiapsiagaan tanggap darurat geologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Rehabilitasi dan rekonstruksi geologi.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Regulasi dan budaya sadar bencana geologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Bahaya dan kerentanan geologi.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana geologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebaga peringatan dini bencana geologi.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Mitigasi pengurangan risiko bencana hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Pencegahan dan kesiapsiagaan, tanggap darurat hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Rehabilitasi dan rekonstruksi hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Regulasi dan budaya sadar bencana hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Bahaya dan kerentanan bencana hidrometeorologi.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana hidrometeorologi","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Mitigasi pengurangan risiko bencana kebakaran lahan dan hutan.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Pencegahan dan kesiapsiagaan tanggap darurat kebakaran lahan dan hutan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Rehabilitasi dan rekonstruksi kebakaran lahan dan hutan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Regulasi dan budaya sadar bencana kebakaran lahan dan hutan.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Revitalisasi nilai budaya lokal dan partisipasi perempuan untuk pencegahan bencana kebakaran hutan, padang penggembalaan, dan lahan produktif","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Bahaya dan kerentanan bencana kebakaran lahan dan hutan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Eksplorasi dan adopsi nilai kearifan lokal dalam pengelolaan lahan dan hutan untuk mencegah bencana kebakaran","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pemberdayaan mitigasi berbasiskan komunitas","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Teknologi peringatan dini bencana alam.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Recovery kehidupan sosial, ekonomi, dan budayamasyarakat pasca bencana.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pengembangan model dan sistem informasi mitigasi bencana","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pemetaan bencana sebagai informasi tata ruang wilayah dan desain bangunan.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana alam","category_research_id"=>"9"],
["research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Mitigasi dampak perubahan iklim.","category_research_id"=>"9"],
["research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Perubahan tutupan lahan dan daya dukung lahan","category_research_id"=>"9"],
["research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Kontribusi dan peran hutan dalam perubahan iklim","category_research_id"=>"9"],
["research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Proses pengelolaan lingkungan yang diakibatkan perubahan tutupan lahan dan perubahan iklim","category_research_id"=>"9"],
["research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Eksplorasi dan adopsi kearifan lokal dalam mengatasi perubahan iklim dan mengelola hutan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Kajian pemetaan kesehatan lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Rehabilitasi ekosistem","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Eksplorasi ramah lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Regulasi dan budaya","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana kebakaran lahan dan hutan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bahaya, kerentanan, risiko dan manajemen bencana biologi (termasuk persebaran penyakit, ledakan serangga, ledakan populasi burung, ikan dll.)","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bioteknologi lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bioremediasi lingkungan.","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Manajemen limbah berbahaya dan beracun","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Adaptasi lingkungan terhadap perubahan iklim dan/atau pencemaran","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Analisis resiko lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Konservasi sumber daya alam","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Valuasi sumber daya alam","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Restorasi kerusakan lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Teknologi pengolahan limbah padat, cair dan gas","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Sistem pengetahuan dan teknologi lokal dalam mengelola sumber daya alam untuk mencegah kerusakan lingkungan","category_research_id"=>"9"],
["research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Pengembangan kebijakan atau peraturan tentang kegiatan produksi dan konsumsi yang pro lingkungan.","category_research_id"=>"9"],
["research_theme"=>"Bencana kegagalan teknologi","research_topic"=>"Bahaya, kerentanan dan risiko kegagalan teknologi","category_research_id"=>"9"],
["research_theme"=>"Bencana kegagalan teknologi","research_topic"=>"Manajemen bencana kegagalan teknologi (termasuk nuklir, konstruksi modern, dll.).","category_research_id"=>"9"],
["research_theme"=>"Bencana sosial","research_topic"=>"Bahaya, kerentanan dan risiko bencana sosial (termasuk kerusakan sosial)","category_research_id"=>"9"],
["research_theme"=>"Bencana sosial","research_topic"=>"Manajemen bencana sosial","category_research_id"=>"9"],
["research_theme"=>"Bencana sosial","research_topic"=>"Kearifan lokal untuk mencegah dan mengatasi bencana sosial","category_research_id"=>"9"],
["research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Wilayah dengan kerentanan tinggi terhadap bencana alam","category_research_id"=>"9"],
["research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Penilaian cerdas terhadap fasilitas umum yang/telah terbangun (smart assessment on existing public facilities)","category_research_id"=>"9"],
["research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Kesiapsiagaan masyarakat menghadapi bencana alam.","category_research_id"=>"9"],
["research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Bencana dan kearifan lokal","category_research_id"=>"9"],
["research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Mitigasi bencana alam berbasis kearifan lokal","category_research_id"=>"9"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Indigenous studies","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Global village","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Identitas, mobilitas, diversity, dan multikulturalisme","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Budaya dalam upaya mencegah dan menangani akibat dari kekerasan, radikalisme, kekerasan berbasis gender, anak, etnisitas, agama, dan identitas lainnya, serta dalam upaya mengembangkan kesejahteraan dan keunggulan prestasi","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Soft power diplomacy","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Komunikasi publik di era revolusi teknologi informasi dan komunikasi","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Tata kelola dan pemerintahan","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Demokrasi, politik, dan pemilihan umum","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Hubungan internasional","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Corporate Social Responsibility (CSR)","category_research_id"=>"10"],
["research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Perempuan dalam penguatan sistem sosialbudaya untuk pembangunan inklusi dan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Urban planning","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Urban transportation","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas berbasis pengetahuan lokal dan pekerja keluarga untuk industri","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas orang, nilai, dan barang serta implikasinya pada transformasi nilai budaya dan perilaku konsumtif dalam era global","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas pada masyarakat lokal dan strategi memelihara lingkungan asal dan tujuan","category_research_id"=>"10"],
["research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas pada perempuan dan kelompok rentan sebagai resiliensi dalam sistem dan struktur masyarakat dalam era global","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Reforma agraria","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Pengentasan kemiskinan dan kemandirian pangan","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Rekayasa sosial dan pengembangan pedesaan","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Modal sosial budaya untuk pencegahan dan penanganan akibat dari kekerasan perempuan dan anak, ketahanan keluarga, dan komunitas minoritas","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Menggali kearifan lokal sebagai modal sosial bagi ketahanan bangsa","category_research_id"=>"10"],
["research_theme"=>"Penguatan modal sosial","research_topic"=>"Modal sosial perempuan dalam ketahanan keluarga, komunitas, dan masyarakat yang berwawasan keadilan gender, perlindungan anak, inklusi sosial, dan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Kewirausahaan, koperasi, dan UMKM","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Perempuan dalam wirausaha, koperasi, dan UMKM berbasis pengetahuan khas perempuan","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Seni-budaya pendukung pariwisata","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Grand design kekayaan intelektual lokal, peninggalan sejarah, dan pelestariannya dalam mendukung karakter bangsa dan pariwisata yang berkesinambungan","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Sumber daya manusia dalam lingkup organisasi industri","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Perempuan sebagai kekuatan sumber daya manusia dalam pembangunan ekonomi yang berorientasi pada keadilan gender, inklusi sosial, & berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Penguatan kapasitas sumber daya manusia yang berorientasi pada keadilan gender, inklusi sosial, dan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Patriarki dan dominasi sosial dalam pembangunan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Grand design pengetahuan lokal dan berbasis pengetahuan lokal perempuan, laki-laki, anak, komunitas minoritas, komunitas berkebutuhan khusus untuk penciptaan daya saing bangsa","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pemetaan, revitalisasi, dan transformasi pengetahuan dan keterampilan berbasis pengetahuan lokal untuk peningkatan daya saing ekonomi bangsa berwawasan gender, inklusi sosial, dan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pembangunan sistem sosial yang mendorong peningkatan, pendistribusian, dan penciptaan sumber daya manusia yang kreatif menghadapi pembangunan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pendidikan berkarakter dan berdaya saing berwawasan keadilan gender, anak, inklusi sosial yang berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Eksplorasi kearifan lokal tentang peran perempuan dalam keluarga dan masyarakat","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Rekayasa sosial dan tata kelola dalam pembangunan yang adil gender, inklusi sosial, dan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Kepemimpinan dan transformasi dalam tata kelola pengarusutamaan gender dalam pembangunan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni tradisi dan pewarisan","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni ritual","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Konservasi seni","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Revitalisasi seni","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan daya saing bangsa","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan kesetaraan gender","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan ideologi bangsa","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Digital ekonomi/smart ekonomi/ekonomi kreatif","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Diaspora dan tenaga kerja migran internasional Indonesia","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Pembudayaan nilai-nilai karakter utama","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Peningkatan kualitas guru dalam penguatan pendidikan karakter","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Integrasi karakter bangsa dalam proses pembelajaran","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Jejaring kemitraan lembaga penyelenggara pendidikan","category_research_id"=>"10"],
["research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Pembentukan identitas melalui eksplorasi sejarah lokal di perbatasan","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Eksplorasi dan difusi teknologi seni","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Seni dan lingkungan","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Seni dan pendidikan","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Seni dan kehidupan masyarakat","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Seni dan pengembangan ekonomi","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Teknologi dan media seni","category_research_id"=>"10"],
["research_theme"=>"Seni","research_topic"=>"Pengembangan seni berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Teknologi pendidikan dan pembelajaran","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Manajemen pendidikan","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Sumber daya pendidikan (tenaga pendidik dan kependidikan)","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Kesetaraan gender dan inklusi sosial dalam pendidikan","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Hasil pendidikan dan pembentukan karakter bangsa","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Internalisasi nilai-nilai kearifan lokal dalam pembelajaran","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Pengembangan manajemen sekolah berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Pendidikan","research_topic"=>"Kurikulum pendidikan karakter berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Eksplorasi kearifan lokal di Nusantara","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Strategi pelestarian kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Eksplorasi sistem pemerintahan lokal sebagai dasar pengembangan tata kelola pemerintahan modern","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Nilai-nilai demokrasi berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Rekayasa sosial dan tata kelola kearifan lokal dalam ketahanan dan daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Kearifan lokal, karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","category_research_id"=>"10"],
["research_theme"=>"Kearifan lokal","research_topic"=>"Perempuan, kearifan lokal, dan karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan ekowisata berbasis kearifan lokal","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pariwisata virtual: kesiapan teknologi dan masa depan","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata kreatif","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Ekonomi kreatif dalam mendukung pembangunan berkelanjutan","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Kebijakan dalam mendorong ekonomi kreatif","category_research_id"=>"10"],
["research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal yang adil gender, inklusi sosial, dan keberlanjutan","category_research_id"=>"10"],


            // tambahkan data lainnya sesuai kebutuhan
        ];

        DB::table('field_focus_research')->insert($data);
    }
}
