<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldFocusReasearchSeeder extends Seeder
{
    /*
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemanfaatan teknik radiasi untuk pencarian galur mutan unggul"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan tanaman dengan teknologi berbasis bioteknologi"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan tanaman teknik konvensional"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan tanaman"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan ternak dengan teknologi berbasis bioteknologi"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Pemuliaan ternak teknik konvensional"],
["id"=>"1","research_theme"=>"Teknologi pemuliaan bibit, tanaman, ternak, dan ikan","research_topic"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan ternak"],
["id"=>"2","research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Modernisasi sistem pertanian dan pemanfaatan lahan"],
["id"=>"2","research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Pertanian lahan sub-optimal basah"],
["id"=>"2","research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Optimasi sistem pertanian tropis"],
["id"=>"2","research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Optimasi sistem pertanian tropis pada komunitas perempuan untuk ketahanan pangan keluarga berbasis pengetahuan lokal"],
["id"=>"2","research_theme"=>"Teknologi budidaya dan pemanfaatan lahan sub-optional","research_topic"=>"Penggunaan kearifan lokal dalam memanfaatkan dan melestarikan lahan dalam rangka keberlanjutan"],
["id"=>"3","research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pengembangan identitas fungsional pertanian"],
["id"=>"3","research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Transformasi antar generasi pekerja pertanian"],
["id"=>"3","research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pergeseran pekerjaan pertanian pada perempuan petani"],
["id"=>"3","research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Keanekaragaman pangan berbasis sumber daya tanaman lokal melalui peran komunitas, perempuan, dan keluarga"],
["id"=>"3","research_theme"=>"Pengembangan sumber daya manusia pertanian","research_topic"=>"Pola pengembangan SDM Pertanian pada masyarakat tradisional/lokal"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Penguatan agroindustri berbahan baku sumber daya lokal"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Pengelolaan dan konservasi sumber daya lahan, air, dan hayati"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Precision agriculture"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Rekayasa mesin-mesin pertanian dan pengolahan"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Teknologi iradiasi pengawetan hasil pertanian"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Diversifikasi dan hilirisasi produk pertanian, perkebunan, peternakan, dan perikanan"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Revitalisasi dan penguatan pengetahuan lokal perempuan petani"],
["id"=>"4","research_theme"=>"Teknologi pascapanen dan rekayasa teknologi pengolahan pangan","research_topic"=>"Pengelolaan, konservasi sumber daya, dan hilirisasi produk berbasis kearifan lokal"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pendukung kemandirian pangan (padi, jagung, dan kedelai) dan tanaman perkebunan"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Kemandirian pangan komoditas ruminansia"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Kemandirian pangan komoditas perairan"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Efisiensi rantai nilai hasil pertanian, perkebunan, peternakan"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan produk pangan berbasis sumber daya tropis"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan produk pangan fungsional"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan teknologi untuk deteksi pemalsuan produk pertanian, peternakan, dan perikanan"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Pengembangan teknologi untuk pengujian produk halal"],
["id"=>"5","research_theme"=>"Teknologi ketahanan dan kemandirian pangan","research_topic"=>"Strategi ketahanan dan kemandirian pangan pada masyarakat tradisional"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Teknologi pendukung konversi ke bahan bakar gas (BBG)"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Dimethyl ether untuk energi rumah tangga dan transportasi"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan komponen converter kit"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi dan produk biogasoline"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan dan pemanfaatan bioenergi untuk transportasi, listrik dan industri"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi dan pemanfaatan fuel cell"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi pembuatan bio-crude oil"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan teknologi pembuatan bioetanol generasi"],
["id"=>"6","research_theme"=>"Teknologi substitusi bahan bakar","research_topic"=>"Pengembangan bahan bakar lokal sebagai substituent bahan bakar fosil"],
["id"=>"7","research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLT panas bumi"],
["id"=>"7","research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLT mikro hidro darat dan marine"],
["id"=>"7","research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"PLT bioenergi (biomass, biogas, biofuel) masif"],
["id"=>"7","research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Rancang bangun PLTB (Bayu)"],
["id"=>"7","research_theme"=>"Kemandirian teknologi pembangkit listrik","research_topic"=>"Restorasi lahan dan inisiasi pengembangan energi listrik berbasis sumber daya lokal"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Bangunan hemat dan mandiri energi"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Sistem smart grid dan manajemen konservasi energi"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Teknologi komponen listrik hemat energi"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Pengembangan sistem microgrid dalam manajemen energi terbarukan"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Teknologi hybrid dalam pemanfaatan sumber energi terbarukan"],
["id"=>"8","research_theme"=>"Teknologi konservasi energi","research_topic"=>"Kearifan lokal dalam arsitektur untuk pengembangan bangunan hemat energi"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pendukung EOR"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Penyiapan infrastruktur PLTN"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pendukung clean coal"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Transfer dan adopsi inovasi diversifikasi energi berbasis komunitas berwawasan gender dan berkelanjutan"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Model transformasi komunitas mandiri energi terbarukan berbasis pengetahuan lokal, komunitas dan masyarakat lokal"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi pengembangan elektrifikasi pedesaan"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Teknologi tepat guna dalam pemanfaatan energi baru dan terbarukan"],
["id"=>"9","research_theme"=>"Teknologi ketahanan, diversifikasi energi dan penguatan komunitas sosial","research_topic"=>"Pengelolaan energi terbarukan berbasis kearifan lokal masyarakat"],
["id"=>"10","research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan produksi vaksin utama (hepatitis, dengue)"],
["id"=>"10","research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan sel punca (stem cell)"],
["id"=>"10","research_theme"=>"Teknologi produk biofarmasetika","research_topic"=>"Penguasaan produk biosimilar dan produk darah"],
["id"=>"11","research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit infeksi"],
["id"=>"11","research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit degeneratif"],
["id"=>"11","research_theme"=>"Teknologi alat kesehatan dan diagnostik","research_topic"=>"Pengembangan alat elektromedik"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan fitofarmaka berbasis sumber daya lokal"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Bahan baku obat kimia"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Saintifikasi jamu dan herbal, teknologi produksi pigmen alami"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan obat tradisional berbasis IPTEKS untuk penyakit-penyakit tropis (neglected diseases)"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Pengembangan teknologi biosimilar, biosintesis, dan biorefinery untuk produksi bahan obat"],
["id"=>"12","research_theme"=>"Teknologi kemandirian bahan baku obat","research_topic"=>"Etnomedisin (daun, akar, umbi, batang, buah)"],
["id"=>"13","research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Penguatan pengetahuan perempuan dalam pengembangan fitofarmaka berbasis pengetahuan lokal"],
["id"=>"13","research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Pengetahuan lokal untuk penggunaan jamu dan herbal dalam kesehatan masyarakat, yang sensitif gender dan inklusif sosial"],
["id"=>"13","research_theme"=>"Pengembangan dan penguatan sistem kelembagaan, kebijakan kesehatan, dan pemberdayaan masyarakat dalam mendukung kemandirian obat","research_topic"=>"Penguatan pengetahuan dan pengembangan kebiasaan masyarakat dalam berperilaku sehat"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mendukung pola hidup bersih dan sehat"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mengatasi wabah penyakit"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal untuk mengatasi stunting dan pola asuh anak dalam keluarga."],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal kaitannya dengan pengolahan makanan sehat dan bergizi"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Identifikasi hambatan budaya dalam tumbuh kembang dan pola asuh anak"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan reproduksi perempuan"],
["id"=>"14","research_theme"=>"Komodifikasi kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan","research_topic"=>"Pengetahuan perempuan tentang kesehatan reproduksi berbasis kearifan lokal"],
["id"=>"15","research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Manajemen keselamatan"],
["id"=>"15","research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Sarana prasarana pendukung keselamatan"],
["id"=>"15","research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Manajemen transportasi ramah gender, anak, dan kelompok berkebutuhan khusus"],
["id"=>"15","research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Kearifan lokal dalam mobilitas masyarakat tradisional"],
["id"=>"15","research_theme"=>"Teknologi dan manajemen keselamatan transportasi nasional","research_topic"=>"Adopsi nilai dan norma masyarakat lokal dalam mengembangkan manajemen keselamatan transportasi"],
["id"=>"16","research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda jalan dan rel"],
["id"=>"16","research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda air"],
["id"=>"16","research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Moda udara"],
["id"=>"16","research_theme"=>"Teknologi penguatan industri transportasi nasional","research_topic"=>"Penguatan industri transportasi yang ramah lingkungan sosial dan budaya"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Sistem cerdas manajemen transportasi"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Teknologi prasarana transportasi"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Sistem konstruksi prasarana transportasi"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Manajemen keselamatan kerja pelaksanaan konstruksi infrastruktur"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Manajemen sistem pengendalian dan penjaminan mutu pelaksanaan konstruksi infrastruktur transportasi"],
["id"=>"17","research_theme"=>"Teknologi infrastruktur dan pendukung sistem transportasi","research_topic"=>"Pelibatan tokoh-tokoh lokal dalam perencanaan pengembangan teknologi infrastruktur sistem transportasi"],
["id"=>"18","research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Riset dasar pendukung teknologi dan sistem transportasi"],
["id"=>"18","research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Sistem sosial yang mendukung partisipasi perempuan, anak, dan inklusi sosial serta dalam penggunaan sarana dan prasarana transportasi"],
["id"=>"18","research_theme"=>"Kajian kebijakan, sosial, dan ekonomi transportasi","research_topic"=>"Pengetahuan lokal untuk pengembangan kebijakan transportasi"],
["id"=>"19","research_theme"=>"Intelligent transportation system","research_topic"=>"Manajemen transportasi perkotaan/urban"],
["id"=>"19","research_theme"=>"Intelligent transportation system","research_topic"=>"Manajemen transportasi logistik"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Teknologi 5G (broadband)"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Telekomunikasi berbasis Internet Protocol (IP) dan Internet of Things (IoT)"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Network, data and information security"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Penyiaran multimedia berbasis digital"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"IT security"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Pengembangan jaringan sensor"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Teknologi antena dan propagasi gelombang radio"],
["id"=>"20","research_theme"=>"Pengembangan infrastruktur TIK","research_topic"=>"Pengembangan sistem radio kognitif"],
["id"=>"21","research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem TIK e-Government"],
["id"=>"21","research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem TIK e-Business"],
["id"=>"21","research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Framework/platform penunjang industri kreatif dan kontrol"],
["id"=>"21","research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem informasi berbasis teknologi pendukung industri mikro berwawasan gender dan berkelanjutan"],
["id"=>"21","research_theme"=>"Pengembangan sistem/platform berbasis Open Source","research_topic"=>"Sistem informasi berbasis kearifan lokal"],
["id"=>"22","research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Teknologi dan konten untuk data informasi geospasial dan inderaja"],
["id"=>"22","research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Pengembangan teknologi big data"],
["id"=>"22","research_theme"=>"Teknologi untuk peningkatan konten TIK","research_topic"=>"Teknologi untuk data informasi berbagai bentuk kearifan lokal di Indonesia"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk sistem jaringan"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk smart city"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk customer premises equipment (CPE)"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Kebijakan dan sosial humaniora pendukung TIK"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Teknologi piranti pendukung partisipasi perempuan, anak, kelompok berkebutuhan khusus, serta keamanan penggunaan informasi berbasis TIK"],
["id"=>"23","research_theme"=>"Teknologi piranti TIK dan pendukung TIK","research_topic"=>"Piranti TIK untuk pelestarian kearifan lokal"],
["id"=>"24","research_theme"=>"Pengembangan sistem berbasis kecerdasan buatan","research_topic"=>"Pengembangan aplikasi sistem cerdas"],
["id"=>"24","research_theme"=>"Pengembangan sistem berbasis kecerdasan buatan","research_topic"=>"Teknologi robot vision"],
["id"=>"25","research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra darat"],
["id"=>"25","research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra laut"],
["id"=>"25","research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Pengembangan produk alat angkut matra udara"],
["id"=>"25","research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Adopsi sistem pengetahuan dan teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara"],
["id"=>"25","research_theme"=>"Teknologi pendukung daya gerak","research_topic"=>"Sistem teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara yang ramah perempuan, anak, dan kelompok rentan"],
["id"=>"26","research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk roket"],
["id"=>"26","research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk handak"],
["id"=>"26","research_theme"=>"Teknologi pendukung daya gempur","research_topic"=>"Pengembangan produk sistem persenjataan"],
["id"=>"27","research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan produk Komando, Kendali, Komunikasi, Komputasi, Integrasi, Pengamatan, dan Pengintaian (K4IPP), terutama radar, alat komunikasi dan satelit"],
["id"=>"27","research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan produk material"],
["id"=>"27","research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan sumber daya pertahanan"],
["id"=>"27","research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Pengembangan sistem sosial pendukung pertahanan dan keamanan berbasis budaya lokal yang berwawasan gender dan inklusi sosial"],
["id"=>"27","research_theme"=>"Teknologi pendukung hankam","research_topic"=>"Sistem hankam berbasis sistem pengetahuan dan teknologi lokal"],
["id"=>"28","research_theme"=>"Penanganan konflik melalui pendekatan sosial budaya","research_topic"=>"Identifikasi nilai-nilai kearifan lokal dalam penanganan konflik"],
["id"=>"28","research_theme"=>"Penanganan konflik melalui pendekatan sosial budaya","research_topic"=>"Adopsi nilai-nilai kearifan lokal untuk menangani konflik"],
["id"=>"29","research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Ekstraksi dan rancang bangun pabrik logam tanah jarang."],
["id"=>"29","research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Pengembangan sel surya berbasis non silicon"],
["id"=>"29","research_theme"=>"Teknologi pengolahan mineral strategis berbahan baku lokal","research_topic"=>"Pengolahan bijih mineral strategis lokal"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Produksi polimer untuk aplikasi separasi di industri"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Material pendukung biosensor dan kemosensor"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan membran"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan katalisator dan biokatalisator (enzim) untuk aplikasi di industri"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Inovasi teknologi material bahan bangunan lokal"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Teknologi ekstraksi aspal dari batuan alami (aspal batu buton)."],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Pengembangan material geopolimer"],
["id"=>"30","research_theme"=>"Teknologi pengembangan material fungsional","research_topic"=>"Inovasi teknologi material bahan bangunan lokal."],
["id"=>"31","research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Desain dan eksplorasi material pigmen absorber"],
["id"=>"31","research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Pendukung transformasi material sampah dan pengolahan limbah"],
["id"=>"31","research_theme"=>"Teknologi eksplorasi potensi material baru","research_topic"=>"Pendukung material struktur"],
["id"=>"32","research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Karakterisasi material berbasis laser dan optik."],
["id"=>"32","research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Karakterisasi material biokompatibel"],
["id"=>"32","research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Kemandirian bahan baku magnet kuat."],
["id"=>"32","research_theme"=>"Teknologi karakterisasi material dan dukungan industri","research_topic"=>"Pengembangan material paduan"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Ketahanan sosial dan penguatan ekonomi pesisir"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Kedaulatan pangan masyarakat pesisir dan pulau terpencil"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengelolaan pesisir perbatasan dari aspek social security dan prosperity"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Diversifikasi, dan pelestarian sumber daya kelautan"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Eksplorasi dan pemanfaatan sumber daya pesisir dan laut"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan teknologi dan manajemen pulaupulau kecil dan pesisir."],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan industri pariwisata bahari"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Pengembangan industri pariwisata bahari di daerah 3T berbasis kearifan lokal"],
["id"=>"33","research_theme"=>"Teknologi kedaulatan daerah 3T (Terdepan, Terluar, Tertinggal)","research_topic"=>"Sistem pengetahuan dan teknologi lokal dalam pelestarian sumber daya laut dan pesisir"],
["id"=>"34","research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Konservasi dan rehabilitasi ekosistem pesisir dan laut."],
["id"=>"34","research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Zonasi ekosistem dan pendukung kawasan konservasi laut."],
["id"=>"34","research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Teknologi konservasi dan rehabilitasi ekosistem pesisir dan laut berbasis kearifan lokal"],
["id"=>"34","research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Eksplorasi nilai-nilai kearifan lokal dalam pengelolaan dan pemanfaatan sumber daya laut dan pesisir."],
["id"=>"34","research_theme"=>"Teknologi konservasi lingkungan maritim","research_topic"=>"Kesehatan dan jasa ekosistem pesisir dan laut"],
["id"=>"35","research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Penguasaan teknologi survei SDE/SDA laut dalam."],
["id"=>"35","research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Pengembangan teknologi wahana pesisir, lepas pantai, dan laut dalam."],
["id"=>"35","research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Penguasaan teknologi komunikasi, navigasi, security, dan supervise"],
["id"=>"35","research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Pengembangan teknologi infrastruktur pantai dan lepas pantai"],
["id"=>"35","research_theme"=>"Teknologi penguatan infrastruktur maritim","research_topic"=>"Integrasi kearifan lokal dalam pengembangan teknologi infrastruktur, komunikasi, dan wahana maritim"],
["id"=>"36","research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Revitalisasi kearifan lokal untuk ketahanan, keluarga dan pelestarian sumber daya kelautan"],
["id"=>"36","research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan, kelompok minoritas, dan keluarga untuk ketahanan, dan diversifikasi produk pengolahan sumber daya kelautan"],
["id"=>"36","research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan, dan inklusi sosial dalam penerimaan dan pemanfaatan pariwisata bahari"],
["id"=>"36","research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Integrasi konservasi lingkungan maritim dalam kurikulum pendidikan yang berwawasan gender dan inklusi sosial."],
["id"=>"36","research_theme"=>"Pemberdayaan dan peningkatan partisipasi perempuan dan inklusi sosial dalam lingkungan kemaritiman","research_topic"=>"Partisipasi perempuan dalam pengembangan, pemeliharaan, dan penguatan infrastruktur pantai dan lepas pantai"],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Mitigasi pengurangan risiko bencana geologi"],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Pencegahan dan kesiapsiagaan tanggap darurat geologi"],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Rehabilitasi dan rekonstruksi geologi."],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Regulasi dan budaya sadar bencana geologi"],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Bahaya dan kerentanan geologi."],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana geologi"],
["id"=>"37","research_theme"=>"Teknologi dan manajemen bencana geologi","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebaga peringatan dini bencana geologi."],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Mitigasi pengurangan risiko bencana hidrometeorologi"],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Pencegahan dan kesiapsiagaan, tanggap darurat hidrometeorologi"],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Rehabilitasi dan rekonstruksi hidrometeorologi"],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Regulasi dan budaya sadar bencana hidrometeorologi"],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Bahaya dan kerentanan bencana hidrometeorologi."],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana hidrometeorologi"],
["id"=>"38","research_theme"=>"Teknologi dan manajemen bencana hidrometeorologi","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana hidrometeorologi"],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Mitigasi pengurangan risiko bencana kebakaran lahan dan hutan."],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Pencegahan dan kesiapsiagaan tanggap darurat kebakaran lahan dan hutan"],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Rehabilitasi dan rekonstruksi kebakaran lahan dan hutan"],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Regulasi dan budaya sadar bencana kebakaran lahan dan hutan."],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Revitalisasi nilai budaya lokal dan partisipasi perempuan untuk pencegahan bencana kebakaran hutan, padang penggembalaan, dan lahan produktif"],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Bahaya dan kerentanan bencana kebakaran lahan dan hutan"],
["id"=>"39","research_theme"=>"Teknologi dan manajemen bencana kebakaran lahan dan hutan","research_topic"=>"Eksplorasi dan adopsi nilai kearifan lokal dalam pengelolaan lahan dan hutan untuk mencegah bencana kebakaran"],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pemberdayaan mitigasi berbasiskan komunitas"],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Teknologi peringatan dini bencana alam."],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Recovery kehidupan sosial, ekonomi, dan budayamasyarakat pasca bencana."],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pengembangan model dan sistem informasi mitigasi bencana"],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Pemetaan bencana sebagai informasi tata ruang wilayah dan desain bangunan."],
["id"=>"40","research_theme"=>"Teknologi dan manajemen bencana alam: gempa bumi, tsunami, banjir bandang, tanah longsor, kekeringan (kemarau), gunung meletus","research_topic"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana alam"],
["id"=>"41","research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Mitigasi dampak perubahan iklim."],
["id"=>"41","research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Perubahan tutupan lahan dan daya dukung lahan"],
["id"=>"41","research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Kontribusi dan peran hutan dalam perubahan iklim"],
["id"=>"41","research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Proses pengelolaan lingkungan yang diakibatkan perubahan tutupan lahan dan perubahan iklim"],
["id"=>"41","research_theme"=>"Mitigasi, perubahan iklim dan tata ekosistem","research_topic"=>"Eksplorasi dan adopsi kearifan lokal dalam mengatasi perubahan iklim dan mengelola hutan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Kajian pemetaan kesehatan lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Rehabilitasi ekosistem"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Eksplorasi ramah lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Regulasi dan budaya"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Teknologi dan aplikasi digital dalam manajemen bencana kebakaran lahan dan hutan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bahaya, kerentanan, risiko dan manajemen bencana biologi (termasuk persebaran penyakit, ledakan serangga, ledakan populasi burung, ikan dll.)"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bioteknologi lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Bioremediasi lingkungan."],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Manajemen limbah berbahaya dan beracun"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Adaptasi lingkungan terhadap perubahan iklim dan/atau pencemaran"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Analisis resiko lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Konservasi sumber daya alam"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Valuasi sumber daya alam"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Restorasi kerusakan lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Teknologi pengolahan limbah padat, cair dan gas"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Sistem pengetahuan dan teknologi lokal dalam mengelola sumber daya alam untuk mencegah kerusakan lingkungan"],
["id"=>"42","research_theme"=>"Teknologi dan manajemen lingkungan","research_topic"=>"Pengembangan kebijakan atau peraturan tentang kegiatan produksi dan konsumsi yang pro lingkungan."],
["id"=>"43","research_theme"=>"Bencana kegagalan teknologi","research_topic"=>"Bahaya, kerentanan dan risiko kegagalan teknologi"],
["id"=>"43","research_theme"=>"Bencana kegagalan teknologi","research_topic"=>"Manajemen bencana kegagalan teknologi (termasuk nuklir, konstruksi modern, dll.)."],
["id"=>"44","research_theme"=>"Bencana sosial","research_topic"=>"Bahaya, kerentanan dan risiko bencana sosial (termasuk kerusakan sosial)"],
["id"=>"44","research_theme"=>"Bencana sosial","research_topic"=>"Manajemen bencana sosial"],
["id"=>"44","research_theme"=>"Bencana sosial","research_topic"=>"Kearifan lokal untuk mencegah dan mengatasi bencana sosial"],
["id"=>"45","research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Wilayah dengan kerentanan tinggi terhadap bencana alam"],
["id"=>"45","research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Penilaian cerdas terhadap fasilitas umum yang/telah terbangun (smart assessment on existing public facilities)"],
["id"=>"45","research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Kesiapsiagaan masyarakat menghadapi bencana alam."],
["id"=>"45","research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Bencana dan kearifan lokal"],
["id"=>"45","research_theme"=>"Mitigasi berkelanjutan terhadap bencana alam","research_topic"=>"Mitigasi bencana alam berbasis kearifan lokal"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Indigenous studies"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Global village"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Identitas, mobilitas, diversity, dan multikulturalisme"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Budaya dalam upaya mencegah dan menangani akibat dari kekerasan, radikalisme, kekerasan berbasis gender, anak, etnisitas, agama, dan identitas lainnya, serta dalam upaya mengembangkan kesejahteraan dan keunggulan prestasi"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Soft power diplomacy"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Komunikasi publik di era revolusi teknologi informasi dan komunikasi"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Tata kelola dan pemerintahan"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Demokrasi, politik, dan pemilihan umum"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Hubungan internasional"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Corporate Social Responsibility (CSR)"],
["id"=>"46","research_theme"=>"Pembangunan dan penguatan sosial budaya","research_topic"=>"Perempuan dalam penguatan sistem sosialbudaya untuk pembangunan inklusi dan berkelanjutan"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Urban planning"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Urban transportation"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas berbasis pengetahuan lokal dan pekerja keluarga untuk industri"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas orang, nilai, dan barang serta implikasinya pada transformasi nilai budaya dan perilaku konsumtif dalam era global"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas pada masyarakat lokal dan strategi memelihara lingkungan asal dan tujuan"],
["id"=>"47","research_theme"=>"Sustainable mobility","research_topic"=>"Mobilitas pada perempuan dan kelompok rentan sebagai resiliensi dalam sistem dan struktur masyarakat dalam era global"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Reforma agraria"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Pengentasan kemiskinan dan kemandirian pangan"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Rekayasa sosial dan pengembangan pedesaan"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Modal sosial budaya untuk pencegahan dan penanganan akibat dari kekerasan perempuan dan anak, ketahanan keluarga, dan komunitas minoritas"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Menggali kearifan lokal sebagai modal sosial bagi ketahanan bangsa"],
["id"=>"48","research_theme"=>"Penguatan modal sosial","research_topic"=>"Modal sosial perempuan dalam ketahanan keluarga, komunitas, dan masyarakat yang berwawasan keadilan gender, perlindungan anak, inklusi sosial, dan berkelanjutan"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Kewirausahaan, koperasi, dan UMKM"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Perempuan dalam wirausaha, koperasi, dan UMKM berbasis pengetahuan khas perempuan"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Seni-budaya pendukung pariwisata"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Grand design kekayaan intelektual lokal, peninggalan sejarah, dan pelestariannya dalam mendukung karakter bangsa dan pariwisata yang berkesinambungan"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Sumber daya manusia dalam lingkup organisasi industri"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Perempuan sebagai kekuatan sumber daya manusia dalam pembangunan ekonomi yang berorientasi pada keadilan gender, inklusi sosial, & berkelanjutan"],
["id"=>"49","research_theme"=>"Ekonomi dan sumber daya manusia","research_topic"=>"Penguatan kapasitas sumber daya manusia yang berorientasi pada keadilan gender, inklusi sosial, dan berkelanjutan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Patriarki dan dominasi sosial dalam pembangunan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Grand design pengetahuan lokal dan berbasis pengetahuan lokal perempuan, laki-laki, anak, komunitas minoritas, komunitas berkebutuhan khusus untuk penciptaan daya saing bangsa"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pemetaan, revitalisasi, dan transformasi pengetahuan dan keterampilan berbasis pengetahuan lokal untuk peningkatan daya saing ekonomi bangsa berwawasan gender, inklusi sosial, dan berkelanjutan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pembangunan sistem sosial yang mendorong peningkatan, pendistribusian, dan penciptaan sumber daya manusia yang kreatif menghadapi pembangunan berkelanjutan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Pendidikan berkarakter dan berdaya saing berwawasan keadilan gender, anak, inklusi sosial yang berkelanjutan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Eksplorasi kearifan lokal tentang peran perempuan dalam keluarga dan masyarakat"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Rekayasa sosial dan tata kelola dalam pembangunan yang adil gender, inklusi sosial, dan berkelanjutan"],
["id"=>"50","research_theme"=>"Pengarusutamaan gender dalam pembangunan","research_topic"=>"Kepemimpinan dan transformasi dalam tata kelola pengarusutamaan gender dalam pembangunan berkelanjutan"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni tradisi dan pewarisan"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni ritual"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Konservasi seni"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Revitalisasi seni"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan daya saing bangsa"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan kesetaraan gender"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Seni dan ideologi bangsa"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Digital ekonomi/smart ekonomi/ekonomi kreatif"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Diaspora dan tenaga kerja migran internasional Indonesia"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Pembudayaan nilai-nilai karakter utama"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Peningkatan kualitas guru dalam penguatan pendidikan karakter"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Integrasi karakter bangsa dalam proses pembelajaran"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Jejaring kemitraan lembaga penyelenggara pendidikan"],
["id"=>"51","research_theme"=>"Seni, identitas, kebudayaan, dan karakter bangsa","research_topic"=>"Pembentukan identitas melalui eksplorasi sejarah lokal di perbatasan"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Eksplorasi dan difusi teknologi seni"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Seni dan lingkungan"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Seni dan pendidikan"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Seni dan kehidupan masyarakat"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Seni dan pengembangan ekonomi"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Teknologi dan media seni"],
["id"=>"52","research_theme"=>"Seni","research_topic"=>"Pengembangan seni berbasis kearifan lokal"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Teknologi pendidikan dan pembelajaran"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Manajemen pendidikan"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Sumber daya pendidikan (tenaga pendidik dan kependidikan)"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Kesetaraan gender dan inklusi sosial dalam pendidikan"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Hasil pendidikan dan pembentukan karakter bangsa"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Internalisasi nilai-nilai kearifan lokal dalam pembelajaran"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Pengembangan manajemen sekolah berbasis kearifan lokal"],
["id"=>"53","research_theme"=>"Pendidikan","research_topic"=>"Kurikulum pendidikan karakter berbasis kearifan lokal"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Eksplorasi kearifan lokal di Nusantara"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Strategi pelestarian kearifan lokal"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Eksplorasi sistem pemerintahan lokal sebagai dasar pengembangan tata kelola pemerintahan modern"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Nilai-nilai demokrasi berbasis kearifan lokal"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Rekayasa sosial dan tata kelola kearifan lokal dalam ketahanan dan daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Kearifan lokal, karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan"],
["id"=>"54","research_theme"=>"Kearifan lokal","research_topic"=>"Perempuan, kearifan lokal, dan karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan ekowisata berbasis kearifan lokal"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata berkelanjutan"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pariwisata virtual: kesiapan teknologi dan masa depan"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata kreatif"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Ekonomi kreatif dalam mendukung pembangunan berkelanjutan"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Kebijakan dalam mendorong ekonomi kreatif"],
["id"=>"55","research_theme"=>"Pariwisata dan ekonomi kreatif","research_topic"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal yang adil gender, inklusi sosial, dan keberlanjutan"],

            // tambahkan data lainnya sesuai kebutuhan
        ];

        DB::table('field_focus_research')->insert($data);
    }
}
