<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ResearchTopicsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["name"=>"Pemanfaatan teknik radiasi untuk pencarian galur mutan unggul","research_theme_id"=>"1"],
            ["name"=>"Pemuliaan tanaman dengan teknologi berbasis bioteknologi","research_theme_id"=>"1"],
            ["name"=>"Pemuliaan tanaman teknik konvensional","research_theme_id"=>"1"],
            ["name"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan tanaman","research_theme_id"=>"1"],
            ["name"=>"Pemuliaan ternak dengan teknologi berbasis bioteknologi","research_theme_id"=>"1"],
            ["name"=>"Pemuliaan ternak teknik konvensional","research_theme_id"=>"1"],
            ["name"=>"Revitalisasi dan peningkatan pengetahuan petani berbasis komunitas dalam pemuliaan ternak","research_theme_id"=>"1"],
            ["name"=>"Modernisasi sistem pertanian dan pemanfaatan lahan","research_theme_id"=>"2"],
            ["name"=>"Pertanian lahan sub-optimal basah","research_theme_id"=>"2"],
            ["name"=>"Optimasi sistem pertanian tropis","research_theme_id"=>"2"],
            ["name"=>"Optimasi sistem pertanian tropis pada komunitas perempuan untuk ketahanan pangan keluarga berbasis pengetahuan lokal","research_theme_id"=>"2"],
            ["name"=>"Penggunaan kearifan lokal dalam memanfaatkan dan melestarikan lahan dalam rangka keberlanjutan","research_theme_id"=>"2"],
            ["name"=>"Pengembangan identitas fungsional pertanian","research_theme_id"=>"3"],
            ["name"=>"Transformasi antar generasi pekerja pertanian","research_theme_id"=>"3"],
            ["name"=>"Pergeseran pekerjaan pertanian pada perempuan petani","research_theme_id"=>"3"],
            ["name"=>"Keanekaragaman pangan berbasis sumber daya tanaman lokal melalui peran komunitas, perempuan, dan keluarga","research_theme_id"=>"3"],
            ["name"=>"Pola pengembangan SDM Pertanian pada masyarakat tradisional/lokal","research_theme_id"=>"3"],
            ["name"=>"Penguatan agroindustri berbahan baku sumber daya lokal","research_theme_id"=>"4"],
            ["name"=>"Pengelolaan dan konservasi sumber daya lahan, air, dan hayati","research_theme_id"=>"4"],
            ["name"=>"Precision agriculture","research_theme_id"=>"4"],
            ["name"=>"Rekayasa mesin-mesin pertanian dan pengolahan","research_theme_id"=>"4"],
            ["name"=>"Teknologi iradiasi pengawetan hasil pertanian","research_theme_id"=>"4"],
            ["name"=>"Diversifikasi dan hilirisasi produk pertanian, perkebunan, peternakan, dan perikanan","research_theme_id"=>"4"],
            ["name"=>"Revitalisasi dan penguatan pengetahuan lokal perempuan petani","research_theme_id"=>"4"],
            ["name"=>"Pengelolaan, konservasi sumber daya, dan hilirisasi produk berbasis kearifan lokal","research_theme_id"=>"4"],
            ["name"=>"Pendukung kemandirian pangan (padi, jagung, dan kedelai) dan tanaman perkebunan","research_theme_id"=>"5"],
            ["name"=>"Kemandirian pangan komoditas ruminansia","research_theme_id"=>"5"],
            ["name"=>"Kemandirian pangan komoditas perairan","research_theme_id"=>"5"],
            ["name"=>"Efisiensi rantai nilai hasil pertanian, perkebunan, peternakan","research_theme_id"=>"5"],
            ["name"=>"Pengembangan produk pangan berbasis sumber daya tropis","research_theme_id"=>"5"],
            ["name"=>"Pengembangan produk pangan fungsional","research_theme_id"=>"5"],
            ["name"=>"Pengembangan teknologi untuk deteksi pemalsuan produk pertanian, peternakan, dan perikanan","research_theme_id"=>"5"],
            ["name"=>"Pengembangan teknologi untuk pengujian produk halal","research_theme_id"=>"5"],
            ["name"=>"Strategi ketahanan dan kemandirian pangan pada masyarakat tradisional","research_theme_id"=>"5"],
            ["name"=>"Teknologi pendukung konversi ke bahan bakar gas (BBG)","research_theme_id"=>"6"],
            ["name"=>"Dimethyl ether untuk energi rumah tangga dan transportasi","research_theme_id"=>"6"],
            ["name"=>"Pengembangan komponen converter kit","research_theme_id"=>"6"],
            ["name"=>"Pengembangan teknologi dan produk biogasoline","research_theme_id"=>"6"],
            ["name"=>"Pengembangan dan pemanfaatan bioenergi untuk transportasi, listrik dan industri","research_theme_id"=>"6"],
            ["name"=>"Pengembangan teknologi dan pemanfaatan fuel cell","research_theme_id"=>"6"],
            ["name"=>"Pengembangan teknologi pembuatan bio-crude oil","research_theme_id"=>"6"],
            ["name"=>"Pengembangan teknologi pembuatan bioetanol generasi","research_theme_id"=>"6"],
            ["name"=>"Pengembangan bahan bakar lokal sebagai substituent bahan bakar fosil","research_theme_id"=>"6"],
            ["name"=>"Rancang bangun PLT panas bumi","research_theme_id"=>"7"],
            ["name"=>"Rancang bangun PLT mikro hidro darat dan marine","research_theme_id"=>"7"],
            ["name"=>"PLT bioenergi (biomass, biogas, biofuel) masif","research_theme_id"=>"7"],
            ["name"=>"Rancang bangun PLTB (Bayu)","research_theme_id"=>"7"],
            ["name"=>"Restorasi lahan dan inisiasi pengembangan energi listrik berbasis sumber daya lokal","research_theme_id"=>"7"],
            ["name"=>"Bangunan hemat dan mandiri energi","research_theme_id"=>"8"],
            ["name"=>"Sistem smart grid dan manajemen konservasi energi","research_theme_id"=>"8"],
            ["name"=>"Teknologi komponen listrik hemat energi","research_theme_id"=>"8"],
            ["name"=>"Pengembangan sistem microgrid dalam manajemen energi terbarukan","research_theme_id"=>"8"],
            ["name"=>"Teknologi hybrid dalam pemanfaatan sumber energi terbarukan","research_theme_id"=>"8"],
            ["name"=>"Kearifan lokal dalam arsitektur untuk pengembangan bangunan hemat energi","research_theme_id"=>"8"],
            ["name"=>"Teknologi pendukung EOR","research_theme_id"=>"9"],
            ["name"=>"Penyiapan infrastruktur PLTN","research_theme_id"=>"9"],
            ["name"=>"Teknologi pendukung clean coal","research_theme_id"=>"9"],
            ["name"=>"Transfer dan adopsi inovasi diversifikasi energi berbasis komunitas berwawasan gender dan berkelanjutan","research_theme_id"=>"9"],
            ["name"=>"Model transformasi komunitas mandiri energi terbarukan berbasis pengetahuan lokal, komunitas dan masyarakat lokal","research_theme_id"=>"9"],
            ["name"=>"Teknologi pengembangan elektrifikasi pedesaan","research_theme_id"=>"9"],
            ["name"=>"Teknologi tepat guna dalam pemanfaatan energi baru dan terbarukan","research_theme_id"=>"9"],
            ["name"=>"Pengelolaan energi terbarukan berbasis kearifan lokal masyarakat","research_theme_id"=>"9"],
            ["name"=>"Penguasaan produksi vaksin utama (hepatitis, dengue)","research_theme_id"=>"10"],
            ["name"=>"Penguasaan sel punca (stem cell)","research_theme_id"=>"10"],
            ["name"=>"Penguasaan produk biosimilar dan produk darah","research_theme_id"=>"10"],
            ["name"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit infeksi","research_theme_id"=>"11"],
            ["name"=>"Pengembangan in vivo diagnostic (IVD) untuk deteksi penyakit degeneratif","research_theme_id"=>"11"],
            ["name"=>"Pengembangan alat elektromedik","research_theme_id"=>"11"],
            ["name"=>"Pengembangan fitofarmaka berbasis sumber daya lokal","research_theme_id"=>"12"],
            ["name"=>"Bahan baku obat kimia","research_theme_id"=>"12"],
            ["name"=>"Saintifikasi jamu dan herbal, teknologi produksi pigmen alami","research_theme_id"=>"12"],
            ["name"=>"Pengembangan obat tradisional berbasis IPTEKS untuk penyakit-penyakit tropis (neglected diseases)","research_theme_id"=>"12"],
            ["name"=>"Pengembangan teknologi biosimilar, biosintesis, dan biorefinery untuk produksi bahan obat","research_theme_id"=>"12"],
            ["name"=>"Etnomedisin (daun, akar, umbi, batang, buah)","research_theme_id"=>"12"],
            ["name"=>"Penguatan pengetahuan perempuan dalam pengembangan fitofarmaka berbasis pengetahuan lokal","research_theme_id"=>"13"],
            ["name"=>"Pengetahuan lokal untuk penggunaan jamu dan herbal dalam kesehatan masyarakat, yang sensitif gender dan inklusif sosial","research_theme_id"=>"13"],
            ["name"=>"Penguatan pengetahuan dan pengembangan kebiasaan masyarakat dalam berperilaku sehat","research_theme_id"=>"13"],
            ["name"=>"Kearifan lokal untuk mendukung pola hidup bersih dan sehat","research_theme_id"=>"14"],
            ["name"=>"Kearifan lokal untuk mengatasi wabah penyakit","research_theme_id"=>"14"],
            ["name"=>"Kearifan lokal untuk mengatasi stunting dan pola asuh anak dalam keluarga.","research_theme_id"=>"14"],
            ["name"=>"Kearifan lokal kaitannya dengan pengolahan makanan sehat dan bergizi","research_theme_id"=>"14"],
            ["name"=>"Identifikasi hambatan budaya dalam tumbuh kembang dan pola asuh anak","research_theme_id"=>"14"],
            ["name"=>"Kearifan lokal di bidang kesehatan untuk menangani permasalahan kesehatan reproduksi perempuan","research_theme_id"=>"14"],
            ["name"=>"Pengetahuan perempuan tentang kesehatan reproduksi berbasis kearifan lokal","research_theme_id"=>"14"],
            ["name"=>"Manajemen keselamatan","research_theme_id"=>"15"],
            ["name"=>"Sarana prasarana pendukung keselamatan","research_theme_id"=>"15"],
            ["name"=>"Manajemen transportasi ramah gender, anak, dan kelompok berkebutuhan khusus","research_theme_id"=>"15"],
            ["name"=>"Kearifan lokal dalam mobilitas masyarakat tradisional","research_theme_id"=>"15"],
            ["name"=>"Adopsi nilai dan norma masyarakat lokal dalam mengembangkan manajemen keselamatan transportasi","research_theme_id"=>"15"],
            ["name"=>"Moda jalan dan rel","research_theme_id"=>"16"],
            ["name"=>"Moda air","research_theme_id"=>"16"],
            ["name"=>"Moda udara","research_theme_id"=>"16"],
            ["name"=>"Penguatan industri transportasi yang ramah lingkungan sosial dan budaya","research_theme_id"=>"16"],
            ["name"=>"Sistem cerdas manajemen transportasi","research_theme_id"=>"17"],
            ["name"=>"Teknologi prasarana transportasi","research_theme_id"=>"17"],
            ["name"=>"Sistem konstruksi prasarana transportasi","research_theme_id"=>"17"],
            ["name"=>"Manajemen keselamatan kerja pelaksanaan konstruksi infrastruktur","research_theme_id"=>"17"],
            ["name"=>"Manajemen sistem pengendalian dan penjaminan mutu pelaksanaan konstruksi infrastruktur transportasi","research_theme_id"=>"17"],
            ["name"=>"Pelibatan tokoh-tokoh lokal dalam perencanaan pengembangan teknologi infrastruktur sistem transportasi","research_theme_id"=>"17"],
            ["name"=>"Riset dasar pendukung teknologi dan sistem transportasi","research_theme_id"=>"18"],
            ["name"=>"Sistem sosial yang mendukung partisipasi perempuan, anak, dan inklusi sosial serta dalam penggunaan sarana dan prasarana transportasi","research_theme_id"=>"18"],
            ["name"=>"Pengetahuan lokal untuk pengembangan kebijakan transportasi","research_theme_id"=>"18"],
            ["name"=>"Manajemen transportasi perkotaan/urban","research_theme_id"=>"19"],
            ["name"=>"Manajemen transportasi logistik","research_theme_id"=>"19"],
            ["name"=>"Teknologi 5G (broadband)","research_theme_id"=>"20"],
            ["name"=>"Telekomunikasi berbasis Internet Protocol (IP) dan Internet of Things (IoT)","research_theme_id"=>"20"],
            ["name"=>"Network, data and information security","research_theme_id"=>"20"],
            ["name"=>"Penyiaran multimedia berbasis digital","research_theme_id"=>"20"],
            ["name"=>"IT security","research_theme_id"=>"20"],
            ["name"=>"Pengembangan jaringan sensor","research_theme_id"=>"20"],
            ["name"=>"Teknologi antena dan propagasi gelombang radio","research_theme_id"=>"20"],
            ["name"=>"Pengembangan sistem radio kognitif","research_theme_id"=>"20"],
            ["name"=>"Sistem TIK e-Government","research_theme_id"=>"21"],
            ["name"=>"Sistem TIK e-Business","research_theme_id"=>"21"],
            ["name"=>"Framework/platform penunjang industri kreatif dan kontrol","research_theme_id"=>"21"],
            ["name"=>"Sistem informasi berbasis teknologi pendukung industri mikro berwawasan gender dan berkelanjutan","research_theme_id"=>"21"],
            ["name"=>"Sistem informasi berbasis kearifan lokal","research_theme_id"=>"21"],
            ["name"=>"Teknologi dan konten untuk data informasi geospasial dan inderaja","research_theme_id"=>"22"],
            ["name"=>"Pengembangan teknologi big data","research_theme_id"=>"22"],
            ["name"=>"Teknologi untuk data informasi berbagai bentuk kearifan lokal di Indonesia","research_theme_id"=>"22"],
            ["name"=>"Piranti TIK untuk sistem jaringan","research_theme_id"=>"23"],
            ["name"=>"Piranti TIK untuk smart city","research_theme_id"=>"23"],
            ["name"=>"Piranti TIK untuk customer premises equipment (CPE)","research_theme_id"=>"23"],
            ["name"=>"Kebijakan dan sosial humaniora pendukung TIK","research_theme_id"=>"23"],
            ["name"=>"Teknologi piranti pendukung partisipasi perempuan, anak, kelompok berkebutuhan khusus, serta keamanan penggunaan informasi berbasis TIK","research_theme_id"=>"23"],
            ["name"=>"Piranti TIK untuk pelestarian kearifan lokal","research_theme_id"=>"23"],
            ["name"=>"Pengembangan aplikasi sistem cerdas","research_theme_id"=>"24"],
            ["name"=>"Teknologi robot vision","research_theme_id"=>"24"],
            ["name"=>"Pengembangan produk alat angkut matra darat","research_theme_id"=>"25"],
            ["name"=>"Pengembangan produk alat angkut matra laut","research_theme_id"=>"25"],
            ["name"=>"Pengembangan produk alat angkut matra udara","research_theme_id"=>"25"],
            ["name"=>"Adopsi sistem pengetahuan dan teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara","research_theme_id"=>"25"],
            ["name"=>"Sistem teknologi lokal dalam mengembangkan produk alat angkut matra darat, laut, dan udara yang ramah perempuan, anak, dan kelompok rentan","research_theme_id"=>"25"],
            ["name"=>"Pengembangan produk roket","research_theme_id"=>"26"],
            ["name"=>"Pengembangan produk handak","research_theme_id"=>"26"],
            ["name"=>"Pengembangan produk sistem persenjataan","research_theme_id"=>"26"],
            ["name"=>"Pengembangan produk Komando, Kendali, Komunikasi, Komputasi, Integrasi, Pengamatan, dan Pengintaian (K4IPP), terutama radar, alat komunikasi dan satelit","research_theme_id"=>"27"],
            ["name"=>"Pengembangan produk material","research_theme_id"=>"27"],
            ["name"=>"Pengembangan sumber daya pertahanan","research_theme_id"=>"27"],
            ["name"=>"Pengembangan sistem sosial pendukung pertahanan dan keamanan berbasis budaya lokal yang berwawasan gender dan inklusi sosial","research_theme_id"=>"27"],
            ["name"=>"Sistem hankam berbasis sistem pengetahuan dan teknologi lokal","research_theme_id"=>"27"],
            ["name"=>"Identifikasi nilai-nilai kearifan lokal dalam penanganan konflik","research_theme_id"=>"28"],
            ["name"=>"Adopsi nilai-nilai kearifan lokal untuk menangani konflik","research_theme_id"=>"28"],
            ["name"=>"Ekstraksi dan rancang bangun pabrik logam tanah jarang.","research_theme_id"=>"29"],
            ["name"=>"Pengembangan sel surya berbasis non silicon","research_theme_id"=>"29"],
            ["name"=>"Pengolahan bijih mineral strategis lokal","research_theme_id"=>"29"],
            ["name"=>"Produksi polimer untuk aplikasi separasi di industri","research_theme_id"=>"30"],
            ["name"=>"Material pendukung biosensor dan kemosensor","research_theme_id"=>"30"],
            ["name"=>"Pengembangan membran","research_theme_id"=>"30"],
            ["name"=>"Pengembangan katalisator dan biokatalisator (enzim) untuk aplikasi di industri","research_theme_id"=>"30"],
            ["name"=>"Inovasi teknologi material bahan bangunan lokal","research_theme_id"=>"30"],
            ["name"=>"Teknologi ekstraksi aspal dari batuan alami (aspal batu buton).","research_theme_id"=>"30"],
            ["name"=>"Pengembangan material geopolimer","research_theme_id"=>"30"],
            ["name"=>"Inovasi teknologi material bahan bangunan lokal.","research_theme_id"=>"30"],
            ["name"=>"Desain dan eksplorasi material pigmen absorber","research_theme_id"=>"31"],
            ["name"=>"Pendukung transformasi material sampah dan pengolahan limbah","research_theme_id"=>"31"],
            ["name"=>"Pendukung material struktur","research_theme_id"=>"31"],
            ["name"=>"Karakterisasi material berbasis laser dan optik.","research_theme_id"=>"32"],
            ["name"=>"Karakterisasi material biokompatibel","research_theme_id"=>"32"],
            ["name"=>"Kemandirian bahan baku magnet kuat.","research_theme_id"=>"32"],
            ["name"=>"Pengembangan material paduan","research_theme_id"=>"32"],
            ["name"=>"Ketahanan sosial dan penguatan ekonomi pesisir","research_theme_id"=>"33"],
            ["name"=>"Kedaulatan pangan masyarakat pesisir dan pulau terpencil","research_theme_id"=>"33"],
            ["name"=>"Pengelolaan pesisir perbatasan dari aspek social security dan prosperity","research_theme_id"=>"33"],
            ["name"=>"Diversifikasi, dan pelestarian sumber daya kelautan","research_theme_id"=>"33"],
            ["name"=>"Eksplorasi dan pemanfaatan sumber daya pesisir dan laut","research_theme_id"=>"33"],
            ["name"=>"Pengembangan teknologi dan manajemen pulaupulau kecil dan pesisir.","research_theme_id"=>"33"],
            ["name"=>"Pengembangan industri pariwisata bahari","research_theme_id"=>"33"],
            ["name"=>"Pengembangan industri pariwisata bahari di daerah 3T berbasis kearifan lokal","research_theme_id"=>"33"],
            ["name"=>"Sistem pengetahuan dan teknologi lokal dalam pelestarian sumber daya laut dan pesisir","research_theme_id"=>"33"],
            ["name"=>"Konservasi dan rehabilitasi ekosistem pesisir dan laut.","research_theme_id"=>"34"],
            ["name"=>"Zonasi ekosistem dan pendukung kawasan konservasi laut.","research_theme_id"=>"34"],
            ["name"=>"Teknologi konservasi dan rehabilitasi ekosistem pesisir dan laut berbasis kearifan lokal","research_theme_id"=>"34"],
            ["name"=>"Eksplorasi nilai-nilai kearifan lokal dalam pengelolaan dan pemanfaatan sumber daya laut dan pesisir.","research_theme_id"=>"34"],
            ["name"=>"Kesehatan dan jasa ekosistem pesisir dan laut","research_theme_id"=>"34"],
            ["name"=>"Penguasaan teknologi survei SDE/SDA laut dalam.","research_theme_id"=>"35"],
            ["name"=>"Pengembangan teknologi wahana pesisir, lepas pantai, dan laut dalam.","research_theme_id"=>"35"],
            ["name"=>"Penguasaan teknologi komunikasi, navigasi, security, dan supervise","research_theme_id"=>"35"],
            ["name"=>"Pengembangan teknologi infrastruktur pantai dan lepas pantai","research_theme_id"=>"35"],
            ["name"=>"Integrasi kearifan lokal dalam pengembangan teknologi infrastruktur, komunikasi, dan wahana maritim","research_theme_id"=>"35"],
            ["name"=>"Revitalisasi kearifan lokal untuk ketahanan, keluarga dan pelestarian sumber daya kelautan","research_theme_id"=>"36"],
            ["name"=>"Partisipasi perempuan, kelompok minoritas, dan keluarga untuk ketahanan, dan diversifikasi produk pengolahan sumber daya kelautan","research_theme_id"=>"36"],
            ["name"=>"Partisipasi perempuan, dan inklusi sosial dalam penerimaan dan pemanfaatan pariwisata bahari","research_theme_id"=>"36"],
            ["name"=>"Integrasi konservasi lingkungan maritim dalam kurikulum pendidikan yang berwawasan gender dan inklusi sosial.","research_theme_id"=>"36"],
            ["name"=>"Partisipasi perempuan dalam pengembangan, pemeliharaan, dan penguatan infrastruktur pantai dan lepas pantai","research_theme_id"=>"36"],
            ["name"=>"Mitigasi pengurangan risiko bencana geologi","research_theme_id"=>"37"],
            ["name"=>"Pencegahan dan kesiapsiagaan tanggap darurat geologi","research_theme_id"=>"37"],
            ["name"=>"Rehabilitasi dan rekonstruksi geologi.","research_theme_id"=>"37"],
            ["name"=>"Regulasi dan budaya sadar bencana geologi","research_theme_id"=>"37"],
            ["name"=>"Bahaya dan kerentanan geologi.","research_theme_id"=>"37"],
            ["name"=>"Teknologi dan aplikasi digital dalam manajemen bencana geologi","research_theme_id"=>"37"],
            ["name"=>"Eksplorasi dan adopsi kearifan lokal sebaga peringatan dini bencana geologi.","research_theme_id"=>"37"],
            ["name"=>"Mitigasi pengurangan risiko bencana hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Pencegahan dan kesiapsiagaan, tanggap darurat hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Rehabilitasi dan rekonstruksi hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Regulasi dan budaya sadar bencana hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Bahaya dan kerentanan bencana hidrometeorologi.","research_theme_id"=>"38"],
            ["name"=>"Teknologi dan aplikasi digital dalam manajemen bencana hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana hidrometeorologi","research_theme_id"=>"38"],
            ["name"=>"Mitigasi pengurangan risiko bencana kebakaran lahan dan hutan.","research_theme_id"=>"39"],
            ["name"=>"Pencegahan dan kesiapsiagaan tanggap darurat kebakaran lahan dan hutan","research_theme_id"=>"39"],
            ["name"=>"Rehabilitasi dan rekonstruksi kebakaran lahan dan hutan","research_theme_id"=>"39"],
            ["name"=>"Regulasi dan budaya sadar bencana kebakaran lahan dan hutan.","research_theme_id"=>"39"],
            ["name"=>"Revitalisasi nilai budaya lokal dan partisipasi perempuan untuk pencegahan bencana kebakaran hutan, padang penggembalaan, dan lahan produktif","research_theme_id"=>"39"],
            ["name"=>"Bahaya dan kerentanan bencana kebakaran lahan dan hutan","research_theme_id"=>"39"],
            ["name"=>"Eksplorasi dan adopsi nilai kearifan lokal dalam pengelolaan lahan dan hutan untuk mencegah bencana kebakaran","research_theme_id"=>"39"],
            ["name"=>"Pemberdayaan mitigasi berbasiskan komunitas","research_theme_id"=>"40"],
            ["name"=>"Teknologi peringatan dini bencana alam.","research_theme_id"=>"40"],
            ["name"=>"Recovery kehidupan sosial, ekonomi, dan budayamasyarakat pasca bencana.","research_theme_id"=>"40"],
            ["name"=>"Pengembangan model dan sistem informasi mitigasi bencana","research_theme_id"=>"40"],
            ["name"=>"Pemetaan bencana sebagai informasi tata ruang wilayah dan desain bangunan.","research_theme_id"=>"40"],
            ["name"=>"Eksplorasi dan adopsi kearifan lokal sebagai peringatan dini bencana alam","research_theme_id"=>"40"],
            ["name"=>"Mitigasi dampak perubahan iklim.","research_theme_id"=>"41"],
            ["name"=>"Perubahan tutupan lahan dan daya dukung lahan","research_theme_id"=>"41"],
            ["name"=>"Kontribusi dan peran hutan dalam perubahan iklim","research_theme_id"=>"41"],
            ["name"=>"Proses pengelolaan lingkungan yang diakibatkan perubahan tutupan lahan dan perubahan iklim","research_theme_id"=>"41"],
            ["name"=>"Eksplorasi dan adopsi kearifan lokal dalam mengatasi perubahan iklim dan mengelola hutan","research_theme_id"=>"41"],
            ["name"=>"Kajian pemetaan kesehatan lingkungan","research_theme_id"=>"42"],
            ["name"=>"Rehabilitasi ekosistem","research_theme_id"=>"42"],
            ["name"=>"Eksplorasi ramah lingkungan","research_theme_id"=>"42"],
            ["name"=>"Regulasi dan budaya","research_theme_id"=>"42"],
            ["name"=>"Teknologi dan aplikasi digital dalam manajemen bencana kebakaran lahan dan hutan","research_theme_id"=>"42"],
            ["name"=>"Bahaya, kerentanan, risiko dan manajemen bencana biologi (termasuk persebaran penyakit, ledakan serangga, ledakan populasi burung, ikan dll.)","research_theme_id"=>"42"],
            ["name"=>"Bioteknologi lingkungan","research_theme_id"=>"42"],
            ["name"=>"Bioremediasi lingkungan.","research_theme_id"=>"42"],
            ["name"=>"Manajemen limbah berbahaya dan beracun","research_theme_id"=>"42"],
            ["name"=>"Adaptasi lingkungan terhadap perubahan iklim dan/atau pencemaran","research_theme_id"=>"42"],
            ["name"=>"Analisis resiko lingkungan","research_theme_id"=>"42"],
            ["name"=>"Konservasi sumber daya alam","research_theme_id"=>"42"],
            ["name"=>"Valuasi sumber daya alam","research_theme_id"=>"42"],
            ["name"=>"Restorasi kerusakan lingkungan","research_theme_id"=>"42"],
            ["name"=>"Teknologi pengolahan limbah padat, cair dan gas","research_theme_id"=>"42"],
            ["name"=>"Sistem pengetahuan dan teknologi lokal dalam mengelola sumber daya alam untuk mencegah kerusakan lingkungan","research_theme_id"=>"42"],
            ["name"=>"Pengembangan kebijakan atau peraturan tentang kegiatan produksi dan konsumsi yang pro lingkungan.","research_theme_id"=>"42"],
            ["name"=>"Bahaya, kerentanan dan risiko kegagalan teknologi","research_theme_id"=>"43"],
            ["name"=>"Manajemen bencana kegagalan teknologi (termasuk nuklir, konstruksi modern, dll.).","research_theme_id"=>"43"],
            ["name"=>"Bahaya, kerentanan dan risiko bencana sosial (termasuk kerusakan sosial)","research_theme_id"=>"44"],
            ["name"=>"Manajemen bencana sosial","research_theme_id"=>"44"],
            ["name"=>"Kearifan lokal untuk mencegah dan mengatasi bencana sosial","research_theme_id"=>"44"],
            ["name"=>"Wilayah dengan kerentanan tinggi terhadap bencana alam","research_theme_id"=>"45"],
            ["name"=>"Penilaian cerdas terhadap fasilitas umum yang/telah terbangun (smart assessment on existing public facilities)","research_theme_id"=>"45"],
            ["name"=>"Kesiapsiagaan masyarakat menghadapi bencana alam.","research_theme_id"=>"45"],
            ["name"=>"Bencana dan kearifan lokal","research_theme_id"=>"45"],
            ["name"=>"Mitigasi bencana alam berbasis kearifan lokal","research_theme_id"=>"45"],
            ["name"=>"Indigenous studies","research_theme_id"=>"46"],
            ["name"=>"Global village","research_theme_id"=>"46"],
            ["name"=>"Identitas, mobilitas, diversity, dan multikulturalisme","research_theme_id"=>"46"],
            ["name"=>"Budaya dalam upaya mencegah dan menangani akibat dari kekerasan, radikalisme, kekerasan berbasis gender, anak, etnisitas, agama, dan identitas lainnya, serta dalam upaya mengembangkan kesejahteraan dan keunggulan prestasi","research_theme_id"=>"46"],
            ["name"=>"Soft power diplomacy","research_theme_id"=>"46"],
            ["name"=>"Komunikasi publik di era revolusi teknologi informasi dan komunikasi","research_theme_id"=>"46"],
            ["name"=>"Tata kelola dan pemerintahan","research_theme_id"=>"46"],
            ["name"=>"Demokrasi, politik, dan pemilihan umum","research_theme_id"=>"46"],
            ["name"=>"Hubungan internasional","research_theme_id"=>"46"],
            ["name"=>"Corporate Social Responsibility (CSR)","research_theme_id"=>"46"],
            ["name"=>"Perempuan dalam penguatan sistem sosialbudaya untuk pembangunan inklusi dan berkelanjutan","research_theme_id"=>"46"],
            ["name"=>"Urban planning","research_theme_id"=>"47"],
            ["name"=>"Urban transportation","research_theme_id"=>"47"],
            ["name"=>"Mobilitas berbasis pengetahuan lokal dan pekerja keluarga untuk industri","research_theme_id"=>"47"],
            ["name"=>"Mobilitas orang, nilai, dan barang serta implikasinya pada transformasi nilai budaya dan perilaku konsumtif dalam era global","research_theme_id"=>"47"],
            ["name"=>"Mobilitas pada masyarakat lokal dan strategi memelihara lingkungan asal dan tujuan","research_theme_id"=>"47"],
            ["name"=>"Mobilitas pada perempuan dan kelompok rentan sebagai resiliensi dalam sistem dan struktur masyarakat dalam era global","research_theme_id"=>"47"],
            ["name"=>"Reforma agraria","research_theme_id"=>"48"],
            ["name"=>"Pengentasan kemiskinan dan kemandirian pangan","research_theme_id"=>"48"],
            ["name"=>"Rekayasa sosial dan pengembangan pedesaan","research_theme_id"=>"48"],
            ["name"=>"Modal sosial budaya untuk pencegahan dan penanganan akibat dari kekerasan perempuan dan anak, ketahanan keluarga, dan komunitas minoritas","research_theme_id"=>"48"],
            ["name"=>"Menggali kearifan lokal sebagai modal sosial bagi ketahanan bangsa","research_theme_id"=>"48"],
            ["name"=>"Modal sosial perempuan dalam ketahanan keluarga, komunitas, dan masyarakat yang berwawasan keadilan gender, perlindungan anak, inklusi sosial, dan berkelanjutan","research_theme_id"=>"48"],
            ["name"=>"Kewirausahaan, koperasi, dan UMKM","research_theme_id"=>"49"],
            ["name"=>"Perempuan dalam wirausaha, koperasi, dan UMKM berbasis pengetahuan khas perempuan","research_theme_id"=>"49"],
            ["name"=>"Seni-budaya pendukung pariwisata","research_theme_id"=>"49"],
            ["name"=>"Grand design kekayaan intelektual lokal, peninggalan sejarah, dan pelestariannya dalam mendukung karakter bangsa dan pariwisata yang berkesinambungan","research_theme_id"=>"49"],
            ["name"=>"Sumber daya manusia dalam lingkup organisasi industri","research_theme_id"=>"49"],
            ["name"=>"Perempuan sebagai kekuatan sumber daya manusia dalam pembangunan ekonomi yang berorientasi pada keadilan gender, inklusi sosial, & berkelanjutan","research_theme_id"=>"49"],
            ["name"=>"Penguatan kapasitas sumber daya manusia yang berorientasi pada keadilan gender, inklusi sosial, dan berkelanjutan","research_theme_id"=>"49"],
            ["name"=>"Patriarki dan dominasi sosial dalam pembangunan","research_theme_id"=>"50"],
            ["name"=>"Grand design pengetahuan lokal dan berbasis pengetahuan lokal perempuan, laki-laki, anak, komunitas minoritas, komunitas berkebutuhan khusus untuk penciptaan daya saing bangsa","research_theme_id"=>"50"],
            ["name"=>"Pemetaan, revitalisasi, dan transformasi pengetahuan dan keterampilan berbasis pengetahuan lokal untuk peningkatan daya saing ekonomi bangsa berwawasan gender, inklusi sosial, dan berkelanjutan","research_theme_id"=>"50"],
            ["name"=>"Pembangunan sistem sosial yang mendorong peningkatan, pendistribusian, dan penciptaan sumber daya manusia yang kreatif menghadapi pembangunan berkelanjutan","research_theme_id"=>"50"],
            ["name"=>"Pendidikan berkarakter dan berdaya saing berwawasan keadilan gender, anak, inklusi sosial yang berkelanjutan","research_theme_id"=>"50"],
            ["name"=>"Eksplorasi kearifan lokal tentang peran perempuan dalam keluarga dan masyarakat","research_theme_id"=>"50"],
            ["name"=>"Rekayasa sosial dan tata kelola dalam pembangunan yang adil gender, inklusi sosial, dan berkelanjutan","research_theme_id"=>"50"],
            ["name"=>"Kepemimpinan dan transformasi dalam tata kelola pengarusutamaan gender dalam pembangunan berkelanjutan","research_theme_id"=>"50"],
            ["name"=>"Seni tradisi dan pewarisan","research_theme_id"=>"51"],
            ["name"=>"Seni ritual","research_theme_id"=>"51"],
            ["name"=>"Konservasi seni","research_theme_id"=>"51"],
            ["name"=>"Revitalisasi seni","research_theme_id"=>"51"],
            ["name"=>"Seni dan daya saing bangsa","research_theme_id"=>"51"],
            ["name"=>"Seni dan kesetaraan gender","research_theme_id"=>"51"],
            ["name"=>"Seni dan ideologi bangsa","research_theme_id"=>"51"],
            ["name"=>"Digital ekonomi/smart ekonomi/ekonomi kreatif","research_theme_id"=>"51"],
            ["name"=>"Diaspora dan tenaga kerja migran internasional Indonesia","research_theme_id"=>"51"],
            ["name"=>"Pembudayaan nilai-nilai karakter utama","research_theme_id"=>"51"],
            ["name"=>"Peningkatan kualitas guru dalam penguatan pendidikan karakter","research_theme_id"=>"51"],
            ["name"=>"Integrasi karakter bangsa dalam proses pembelajaran","research_theme_id"=>"51"],
            ["name"=>"Jejaring kemitraan lembaga penyelenggara pendidikan","research_theme_id"=>"51"],
            ["name"=>"Pembentukan identitas melalui eksplorasi sejarah lokal di perbatasan","research_theme_id"=>"51"],
            ["name"=>"Eksplorasi dan difusi teknologi seni","research_theme_id"=>"52"],
            ["name"=>"Seni dan lingkungan","research_theme_id"=>"52"],
            ["name"=>"Seni dan pendidikan","research_theme_id"=>"52"],
            ["name"=>"Seni dan kehidupan masyarakat","research_theme_id"=>"52"],
            ["name"=>"Seni dan pengembangan ekonomi","research_theme_id"=>"52"],
            ["name"=>"Teknologi dan media seni","research_theme_id"=>"52"],
            ["name"=>"Pengembangan seni berbasis kearifan lokal","research_theme_id"=>"52"],
            ["name"=>"Teknologi pendidikan dan pembelajaran","research_theme_id"=>"53"],
            ["name"=>"Manajemen pendidikan","research_theme_id"=>"53"],
            ["name"=>"Sumber daya pendidikan (tenaga pendidik dan kependidikan)","research_theme_id"=>"53"],
            ["name"=>"Kesetaraan gender dan inklusi sosial dalam pendidikan","research_theme_id"=>"53"],
            ["name"=>"Hasil pendidikan dan pembentukan karakter bangsa","research_theme_id"=>"53"],
            ["name"=>"Internalisasi nilai-nilai kearifan lokal dalam pembelajaran","research_theme_id"=>"53"],
            ["name"=>"Pengembangan manajemen sekolah berbasis kearifan lokal","research_theme_id"=>"53"],
            ["name"=>"Kurikulum pendidikan karakter berbasis kearifan lokal","research_theme_id"=>"53"],
            ["name"=>"Eksplorasi kearifan lokal di Nusantara","research_theme_id"=>"54"],
            ["name"=>"Strategi pelestarian kearifan lokal","research_theme_id"=>"54"],
            ["name"=>"Eksplorasi sistem pemerintahan lokal sebagai dasar pengembangan tata kelola pemerintahan modern","research_theme_id"=>"54"],
            ["name"=>"Nilai-nilai demokrasi berbasis kearifan lokal","research_theme_id"=>"54"],
            ["name"=>"Rekayasa sosial dan tata kelola kearifan lokal dalam ketahanan dan daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","research_theme_id"=>"54"],
            ["name"=>"Kearifan lokal, karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","research_theme_id"=>"54"],
            ["name"=>"Perempuan, kearifan lokal, dan karya kreatif dan daya saing bangsa daya saing bangsa yang adil gender, inklusi sosial, dan keberlanjutan","research_theme_id"=>"54"],
            ["name"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal","research_theme_id"=>"55"],
            ["name"=>"Pengembangan ekowisata berbasis kearifan lokal","research_theme_id"=>"55"],
            ["name"=>"Pengembangan pariwisata berkelanjutan","research_theme_id"=>"55"],
            ["name"=>"Pariwisata virtual: kesiapan teknologi dan masa depan","research_theme_id"=>"55"],
            ["name"=>"Pengembangan pariwisata kreatif","research_theme_id"=>"55"],
            ["name"=>"Ekonomi kreatif dalam mendukung pembangunan berkelanjutan","research_theme_id"=>"55"],
            ["name"=>"Kebijakan dalam mendorong ekonomi kreatif","research_theme_id"=>"55"],
            ["name"=>"Pengembangan pariwisata dan ekonomi kreatif berbasis kearifan lokal yang adil gender, inklusi sosial, dan keberlanjutan","research_theme_id"=>"55"],
        ];

        foreach ($data as $item) {
            DB::table('research_topics')->insert([
                'name' => $item['name'],
                'research_theme_id' => $item['research_theme_id'],
            ]);
        }
    }
}
